### ISSUE TITLE
Memory Corruption seems to happen a lot

### ISSUE THREAD

**Issue by ApolloTeam-dev** [ApolloTeam-dev/AROS#4]
.   Mostly observered when running Magellan.  Serial debug output shows something like this

################################################################################
#                               Software Failure!                              #
#                           Task : 0x011E5020 - dopus                          #
#            Error: 0x8100000C - Sanity check on memory list failed            #
################################################################################
PC   : 0x00F87E0A
Memory manager data:
In AllocMem, size 56
Corrupted MemChunk 0x010d9040 (next 0x00163ee8, size 1522696)
Previous MemChunk 0x010d8f88 (next 0x010d9040, size 8)
MemHeader 0x01000000 (0x01000020 - 0x08000000)
################################################################################

**Comment by ronybeck** [comment]
So this issue has turned out to be more about Opus 5 crashing than general crashing.  Cotter noticed that swapping out the workbenchl.library that he was using led to a more reliable result.  In his words: about 99% of the crashes are gone.  Based on this evidence alone, I would say that this issue was all about a broken workbench.library and nothinf about memory corruption.

note: using the Aros workbench.library also seems to be quite stable.  Although extensive tests have not been done.

I am closing this issue for now.
